/**
 * PEDAGOGY CONSTANTS
 * Structured data for the "Study Mode" (Capa Pedagógica)
 * Based on the "Arquitecturas de la Temporalidad" thesis.
 */

export interface PedagogyMicro {
  [key: string]: string;
}

export type PedagogyVoice = 'technical' | 'literary';

export interface PedagogyMeso {
  title: string;
  condition: string;
  template: string;
}

export interface PedagogyMacro {
  title: string;
  content: string;
}

export const PEDAGOGY = {
  micro: {
    pulses: "E(k, n): k onsets distribuidos en n pasos por Bjorklund (máxima uniformidad). Densidad ρ = k/n. Rango: [0, n]. ↑k → patrón más saturado; k/n = 1 = four-on-the-floor. E(5,12) ≈ 0.42 → Soleá; E(3,8) = 0.375 → Tresillo cubano.",
    steps: "Cardinalidad n del anillo cíclico ℤ/nℤ donde se distribuyen los pulsos. Rango: [2, 32]. n par → simetría binaria (4/4, 6/8); n primo → asimetría máxima (7, 11, 13 impiden subdivisiones iguales). n=12 → compás de amalgama 12/8; n=16 → rejilla estándar de caja de ritmos.",
    offset: "Rotación cíclica σʳ: desplaza el patrón r posiciones sin alterar su estructura interválica. Rango: [0, n-1]. Equivalente a seleccionar un modo del patrón (como modos de una escala). σ² sobre E(5,12) de Soleá → acentuación de Bulería.",
    probability: "Cada onset sigue una distribución Bernoulli(p). Hits esperados = k·p; varianza = k·p·(1-p). Rango: [0, 1]. p=1 → patrón determinista; p=0.5 → máxima entropía binaria por step. Permite secuenciación generativa donde el silencio es estructural.",
    chaos: "Factor β que modula p → p' = p^(1/(1+β)), comprimiendo las probabilidades hacia la incertidumbre. Rango: [0, 1]. β=0 → sin efecto; β=1 → p'≈√p, los steps probables pierden certeza. Desintegra patrones rígidos en nubes estocásticas tipo Autechre.",
    evolve: "Mutación cíclica: cada N ciclos (speed), cada step tiene 50% de ser perturbado por δ ∈ [-rate, +rate], clamp [0,1]. Rate: [1-30%], Speed: [1-8x]. Genera drift paramétrico: el patrón diverge del original como un proceso de Markov sin estado absorbente.",
    bpm: "Pulso maestro. Período por beat T = 60/BPM (seg); resolución por step = T/n. Rango: [40, 300]. A 120 BPM con n=16, cada step = 31.25ms. BPMs altos comprimen el jitter perceptible; BPMs bajos exponen cada micro-variación.",
    swing: "Desplazamiento determinista de tiempos pares: t' = t_grid + α·(t_next − t_grid), α ∈ [0, 0.75]. α=0 → rejilla recta; α=0.67 → shuffle ternario (triplet feel). Herencia directa de la MPC-3000 de Roger Linn. α=0.5 → groove estándar boom-bap.",
    dynamics: "Rango de velocity [v_min, v_max] asignado a cada onset. Rango del slider: [0, 1] como proporción del rango total. Dinámica alta → acentuación orgánica por distribución uniforme en el rango; dinámica baja → velocidad plana (metrónomo). En flamenco, el acento define el palo.",
    jitter: "Desplazamiento temporal gaussiano 𝒩(0, σ²) aplicado a cada onset en ms. σ proporcional al valor del slider. Rango: [0, ~50ms]. Altera los IOI (Inter-Onset Intervals) simulando imprecisión humana. σ < 10ms → humanización sutil; σ > 30ms → inestabilidad rítmica tipo glitch.",
    volume: "Ganancia lineal de la pista en el bus de mezcla. Rango: [0, 1] → [-∞, 0] dB. Define la jerarquía rítmica: qué elemento es ancla estructural (kick) y cuál es ornamento (hat). No es solo nivel — es peso perceptual en la polirritmia.",
    delaySend: "Nivel de envío al bus de delay (feedback loop). Rango: [0, 1]. Genera repeticiones que crean polirritmias fantasma: un onset en step k produce ecos en k+d, k+2d… reforzando o contradiendo la geometría euclidiana original.",
    reverbSend: "Nivel de envío al bus de reverberación. Rango: [0, 1]. Sitúa el onset en un espacio acústico simulado (RT60). Envíos altos difuminan la precisión temporal del patrón, creando una «niebla» donde el ritmo emerge como textura continua.",
    sampleRoi: "Región de Interés [start, end] dentro del buffer de audio, en proporción normalizada [0, 1]. Define qué segmento del sample se reproduce. Permite micro-cirugía: extraer solo el transiente de ataque (0-5%) o la cola tonal (80-100%).",
    pitch: "Transposición en semitonos por resampling. Rango: [-24, +24] st. Altera frecuencia (f' = f · 2^(st/12)) y duración inversamente. Pitch negativo → bombo profundo desde un chasquido; pitch positivo → micro-glitch de alta frecuencia desde un golpe grave.",
    grainSize: "Ventana temporal de cada grano en síntesis granular, en ms. Rango: [1, 500ms]. >50ms → fragmentos tonales reconocibles; 20-50ms → zona transicional; <20ms → textura de ruido (el grano es más corto que un ciclo de onda audible).",
    overlap: "Factor de superposición entre granos consecutivos. Rango: [1, 8x]. Overlap alto → densidad de nube sedosa y continua (cloud); overlap bajo → stutter rítmico donde cada grano es un evento discreto. Define la transición de granular percusivo a textural.",
    spray: "Dispersión aleatoria del puntero de lectura del grano respecto a la posición ROI. Rango: [0, 1] como proporción del buffer. Spray=0 → lectura secuencial fiel; spray=1 → posición totalmente aleatoria. Convierte audio reconocible en atmósfera abstracta.",
    bitCrush: "Reducción de resolución digital: requantiza la amplitud a 2^b niveles. Rango: [2, 16] bits. 16 bits → CD quality; 8 bits → estética retro/chiptune; 4 bits → distorsión de cuantización agresiva con armónicos no lineales.",
    reverbMix: "Proporción wet/dry del bus global de reverberación. Rango: [0, 1]. Controla cuánto del espacio acústico simulado se mezcla con la señal directa. Mix=0 → sonido seco e íntimo; mix=1 → todo es reverberación, el ataque se disuelve en el espacio. El RT60 define el tamaño de la sala virtual.",
    delayMix: "Proporción wet/dry del bus global de delay. Rango: [0, 1]. Define la prominencia de las repeticiones respecto a la señal original. Mix bajo → eco sutil que refuerza el groove; mix alto → las repeticiones dominan creando un paisaje rítmico de ecos.",
    delayFeedback: "Coeficiente de retroalimentación del delay: cada repetición se re-inyecta multiplicada por este factor. Rango: [0, 1]. Feedback=0 → un solo eco (slap-back); feedback=0.9 → cascada de repeticiones que decaen lentamente; feedback≈1 → auto-oscilación infinita, territorio dub/industrial.",
    fxHighPass: "Filtro paso-alto (HPF) en la cadena global de efectos. Frecuencia de corte en Hz. Rango: [20, 2000]. Elimina frecuencias por debajo del corte con pendiente de 12dB/oct. Útil para limpiar sub-graves del delay/reverb que enturbiarían la mezcla. A 500Hz+ → efecto radio/telefónico.",
    fxLowPass: "Filtro paso-bajo (LPF) en la cadena global de efectos. Frecuencia de corte en Hz. Rango: [500, 20000]. Elimina frecuencias por encima del corte. Suaviza los armónicos agresivos del delay/bitcrush. A <2kHz → efecto lo-fi analógico; a 20kHz → transparente.",
    monitorTemporal: "Visualización del jitter temporal en tiempo real. Muestra la distribución de las desviaciones de timing respecto a la rejilla teórica. Una campana estrecha = precisión mecánica; una distribución ancha = humanización. Permite diagnosticar visualmente si el micro-timing suena 'vivo' o 'robótico'.",
    monitorDistribution: "Histograma de energía por posición en el patrón. Revela qué steps concentran más hits a lo largo del tiempo, considerando probabilidades y caos. Un histograma plano = energía uniforme; picos pronunciados = acentuación emergente. Es el 'mapa de calor' del ritmo.",
    monitorRange: "Medidor del rango dinámico efectivo. Muestra la distribución de velocities (intensidades) generadas. Rango estrecho = patrón plano y mecánico; rango amplio = expresividad dinámica. El dynamics slider define los límites, pero la distribución real depende de la probabilidad y el caos.",
    monitorScatter: "Diagrama de dispersión que cruza timing (eje X) con velocity (eje Y) para cada hit. Revela correlaciones entre micro-timing y dinámica. Un cluster compacto = máquina de ritmos; dispersión amplia = percusionista humano. Es la huella digital del groove.",
    patternSync: "Sincronía del Patrón: mide el MCM (Mínimo Común Múltiplo) de los steps de todas las pistas activas. MCM = punto donde todos los ciclos coinciden simultáneamente en el beat 1. MCM bajo → los patrones se realinean rápido (sensación de estabilidad); MCM alto (>1000) → zona de evolución cuasi-infinita donde la repetición exacta es imperceptible. Es la métrica fundamental de la complejidad polirrítmica.",
    rhythmicEntropy: "Índice de entropía rítmica H = -Σ pᵢ·log₂(pᵢ) calculado sobre la distribución de probabilidades, jitter y caos de todas las pistas. H bajo → determinismo, patrones predecibles; H alto → máxima incertidumbre, territorio generativo. Combina chaos, evolve y jitter en un solo indicador de 'vida' del sistema.",
    mcmValue: "Mínimo Común Múltiplo (MCM/LCM) de los valores de steps de todas las pistas activas. Determina cuántos pasos transcurren antes de que todos los patrones vuelvan a coincidir en su posición inicial. MCM=16 con dos pistas de 8 y 16 → ciclo corto; MCM=1001 con pistas de 7, 11 y 13 → ciclo astronómico.",
    syncImpact: "Impacto de sincronización: porcentaje que indica cuánto contribuye cada pista a la complejidad del MCM global. Calculado como la proporción entre el MCM con y sin esa pista. Un impacto alto significa que eliminar esa pista simplificaría drásticamente el ciclo global.",
    phaseRadar: "Radar de fase circular que visualiza la posición actual de cada pista dentro de su ciclo individual. Cada pista se representa como un punto en un anillo proporcional a sus steps. Cuando todos los puntos se alinean → momento de sincronía (beat 1 global). La velocidad angular de cada punto depende de n: pistas con más steps giran más lento.",
    eclipseCountdown: "Countdown en tiempo real hasta el próximo eclipse rítmico (momento en que todos los patrones coinciden en el beat 1). Calculado como (MCM − step_actual) × duración_semicorchea. Cuando MCM es bajo (16-32), los eclipses son frecuentes y el countdown se recicla rápido. Con MCM alto (>1000), el eclipse puede tardar minutos, indicando una poliritmia de evolución lenta donde la repetición exacta es imperceptible.",
    hitRate: "Porcentaje de onsets que realmente sonaron vs los que fueron programados por el algoritmo euclidiano. Hit Rate = hits / (hits + misses) × 100. Con probabilidad=1 y chaos=0, el hit rate es 100% (determinista). Al activar Chaos o reducir la probabilidad, los onsets se filtran estocásticamente y el hit rate baja, indicando cuánto silencio activo está generando el sistema. Es el termómetro de la densidad efectiva del patrón.",
    fmRatio: "Harmonicity — relación de frecuencia entre portadora y modulador. Valores enteros (1, 2, 3) = timbres armónicos. Valores no enteros (1.5, 2.718) = inarmónicos, metálicos. Autechre usa ratios irracionales para leads que suenan 'rotos pero musicales'.",
    fmIndex: "Modulación Index — profundidad del FM. A 0 suena como el oscilador puro. A 10 empieza la riqueza armónica. A 30+ el espectro colapsa en ruido denso. Aphex Twin usa índices >50 para sus leads más agresivos.",
    wfAmount: "Intensidad del wavefolding — cuántas veces se dobla la onda sobre sí misma. A 0 es el triángulo puro. A 3-4 aparecen los armónicos característicos del Buchla. A 8+ el timbre colapsa en densidad espectral máxima. Técnica §7.1 del documento IDM.",
    wfSymmetry: "Sesgo de la curva de wavefold — desplaza el punto de doblez respecto al centro. A 0 es simétrico (armónicos pares e impares). Positivo enfatiza impares. Negativo crea asimetría que el oído percibe como 'calidez' o 'suciedad' según el contexto.",
    addPartials: "Número de parciales armónicos activos. 2 = fundamental + octava, timbre hueco. 4 = timbre completo natural. 8 = denso, rico, casi como un instrumento acústico. Cada parcial es un oscilador sine a frecuencia n×fundamental.",
    addBrightness: "Pendiente espectral — mezcla entre caída natural (1/n, oscuro) y amplitud plana (todos iguales, brillante). A 0 los graves dominan. A 1 todos los parciales tienen el mismo peso — timbre metálico, artificial. Additive synthesis pura de Yamaha DX7 usaba pendientes intermedias.",
    arRate: "Frecuencia del LFO de audio-rate (20-2000Hz). Por debajo de 20Hz es vibrato/tremolo convencional. Entre 20-100Hz crea sidebands audibles — nuevas frecuencias que no existían en la señal original. A 440Hz el LFO crea una frecuencia diferencia audible. Técnica §6.3 IDM.",
    arDepth: "Profundidad de la modulación audio-rate en Hz. A 0 el LFO está parado — sin efecto. A 100Hz crea sidebands sutiles. A 1000Hz+ el timbre cambia radicalmente — aparecen frecuencias de diferencia e intermodulación que el oído interpreta como inarmónicas o metálicas.",
    // Ratchet & MM
    ratchet: "Retrigger por step: subdivide la duración del step en n+1 disparos equidistantes con curva de decay exponencial v(r) = v₀·0.65ʳ. Rango: [0, 4]. Ratchet=0 → disparo único; ratchet=2 → tripleta interna (3 disparos). Emula el redoble de cajón flamenco o el hi-hat trap de 32nds. A BPMs altos, ratchet ≥3 comprime los retriggers al límite de resolución temporal (~8ms).",
    metricModulation: "Modulación métrica: BPM' = BPM × (a/b) donde a/b ∈ {3/2, 4/3, 5/4, 2/3, 3/4, 4/5}. Rango resultante: [40, 240]. Convierte una subdivisión percibida en el nuevo beat. Ej: 120 × 3/2 = 180 — el tresillo se convierte en negra. Técnica de Stravinsky (Rite of Spring) y Nancarrow (Studies for Player Piano). Modulaciones encadenadas crean derivas de tempo exponenciales.",
    // Layer 2
    layer2Blend: "Mezcla entre sample principal (Layer 1) y capa secundaria (Layer 2). Rango: [0, 1]. A 0 solo suena Layer 1; a 1 suena exclusivamente Layer 2. La crossfade es lineal en amplitud. Permite crear timbres híbridos: kick con capa de textura, hat con capa de ruido granular.",
    layer2Pitch: "Transposición independiente de Layer 2 por resampling. Rango: [-24, +24] st. Independiente del pitch de Layer 1. f₂' = f₂ · 2^(st/12). Permite detuning entre capas (ej: +7st = quinta) para crear intervalos fijos o texturas inarmónicas cuando se combinan capas de timbre diferente.",
    layer2Offset: "Desplazamiento temporal de Layer 2 respecto al onset principal. Rango: [0, 500ms]. A 0ms ambas capas disparan simultáneamente. A 50-100ms crea un efecto de 'flam' (doble ataque). A >200ms Layer 2 actúa como cola o eco seco. Define la micro-estructura temporal dentro de un solo step.",
    layer2Filter: "Filtro paso-bajo (LPF) aplicado exclusivamente a Layer 2. Rango: [200, 8000Hz], pendiente 12dB/oct. Permite oscurecer la capa secundaria para que actúe como cuerpo/resonancia sin competir con el ataque de Layer 1. A 200Hz solo pasan sub-graves; a 8000Hz el filtro es transparente.",
    // Advanced Synths
    padVoices: "Número de osciladores en unísono del sintetizador PAD. Rango: [3, 7]. Cada voz se detuna ligeramente respecto a la fundamental según padDetune. 3 voces → acorde tríada implícito; 7 voces → densidad coral tipo Juno-60 con batimiento (beating) complejo entre armónicos cercanos.",
    padDetune: "Spread de detuning en cents entre las voces del PAD. Rango: [0, 100 cents]. 0 → unísono perfecto (sin batimiento); 15-30 → chorus clásico; 50-100 → cluster microtonalmente denso. El batimiento resultante f_beat = |f₁-f₂| crea una modulación de amplitud periódica que el oído percibe como 'anchura'.",
    padAttack: "Tiempo de ataque de la envolvente del PAD en segundos. Rango: [0.01, 2.0]. 0.01s → ataque percusivo (click + pad); 0.3s → entrada suave estándar; 2.0s → swell glacial donde el acorde emerge como niebla. Define si el PAD marca el ritmo euclidiano o lo disuelve.",
    droneFeedback: "Coeficiente de feedback del delay loop que sostiene el drone. Rango: [0.70, 0.98]. A 0.70 el drone decae en ~1s (burst). A 0.98 el drone se sostiene >30s (bordón infinito). Valores >0.95 crean acumulación armónica por superposición de ciclos. Es el equivalente digital de la cuerda de bordón de la guitarra flamenca.",
    droneFilterFreq: "Frecuencia del LPF en el loop de feedback del drone. Rango: [200, 8000Hz]. Controla el brillo del tono sostenido. A 200Hz solo sobrevive la fundamental (bordón oscuro); a 8000Hz los armónicos superiores se preservan (drone brillante). Emula la resonancia de una cuerda metálica vs una de nylon.",
    ksDecay: "Feedback del loop de Karplus-Strong — controla el sustain de la cuerda virtual. Rango: [0.80, 0.999]. A 0.80 la cuerda se apaga en <100ms (pizzicato seco). A 0.999 vibra >5s (cuerda de sitar). El algoritmo KS es síntesis física: un pulso de ruido filtrado en un delay loop = cuerda pulsada. Inventado por Karplus y Strong en 1983.",
    ksBrightness: "Frecuencia del LPF en el loop KS. Rango: [500, 8000Hz]. Simula el material de la cuerda: 500Hz → cuerda de gut (guitarra barroca); 3000Hz → nylon clásico; 8000Hz → acero brillante. Cada ciclo del loop pierde los armónicos por encima del corte, emulando la disipación natural de energía en una cuerda real.",
    modalBody: "Tipo de resonador modal: 'bell' (campana — frecuencias inarmónicas espaciadas por ×2.09, ×3.43), 'plate' (placa — modos densos y cercanos), 'string' (cuerda — serie armónica natural 1:2:3:4). Define la estructura de parciales del resonador. La síntesis modal descompone un cuerpo vibrante en sus frecuencias propias.",
    modalDecay: "Multiplicador de decay de los modos resonantes. Rango: [0.5, 3.0]. A 0.5 los modos se extinguen rápido (golpe seco). A 3.0 resuenan prolongadamente (gong). Los modos agudos decaen más rápido que los graves (decay_n = base_decay / n), emulando la física real de cuerpos vibrantes.",
    ambientVolume: "Volumen de los loops ambient generativos. Rango: [0.1, 1.0]. Controla el nivel de la textura atmosférica respecto al patrón rítmico. A 0.1 → apenas perceptible (subliminal); a 1.0 → dominante (el ritmo emerge desde la textura). Define la relación figura-fondo sonora.",
    ambientSpeed: "Multiplicador de velocidad de los loops ambient. Rango: [0.5, 2.0]. A 0.5 → tiempo dilatado, texturas glaciales; a 1.0 → velocidad nominal; a 2.0 → granulado acelerado. Altera la densidad temporal de la textura sin afectar el pitch (timestretch implícito).",
    // Round Robin & Phase Drift
    roundRobin: "Micro-variación estocástica por hit (Round Robin). Aplica fluctuación gaussiana 𝒩(0, σ²) sobre la velocity de cada disparo, donde σ = amount × 0.15 × v_max. Rango amount: [0, 100%]. Elimina el 'machine gun effect' de la repetición idéntica. En pistas tonales, rota secuencialmente los noteIndices del array, creando melodías cíclicas desde un patrón rítmico fijo. En samplers, la variación se restringe a velocity/filtro (no pitch) por limitaciones del GrainPlayer.",
    phaseDrift: "Desfase progresivo estilo Steve Reich: acumula un offset temporal Δt por ciclo. Rate: [-0.05, +0.05] seg/ciclo. Rate positivo → la pista se retrasa gradualmente; negativo → se adelanta. A rate=0.01, tras 100 ciclos el desfase es de 1 segundo completo. Genera phasing — el proceso donde dos patrones idénticos divergen lentamente hasta crear interferencias rítmicas complejas antes de re-sincronizarse (o no). Técnica central de 'Piano Phase' (Reich, 1967).",
    cloudMode: "Modo de reproducción de la pista Atmosphere. 'Granular' usa GrainPlayer con parámetros optimizados para texturas (grainSize=500, spray=200, attack=2s). 'Eno' genera 4 bucles asíncronos del sample con duraciones no-sincronizadas (2.3s, 3.7s, 5.1s, 7.3s × enoSpeed), aleatorizando la posición de lectura en cada ciclo. Inspirado en las Ambient installations de Brian Eno donde la no-repetición emerge de ciclos superpuestos de longitudes irracionales.",
    enoSpeed: "Multiplicador de velocidad de los 4 bucles del modo Eno. Rango: [0.5, 2.0]. Escala las duraciones base (2.3s, 3.7s, 5.1s, 7.3s) proporcionalmente. A 0.5 → texturas glaciales, evolución lenta tipo 'Music for Airports'. A 2.0 → ciclos más cortos, mayor densidad de cambios. No altera el pitch del sample (timestretch implícito). Las duraciones base son primos aproximados para maximizar el MCM del ciclo completo.",
    // Phase 4 — L-System, Cellular Automata, Markov
    patternMode: "Selector del motor generativo del patrón rítmico. Euclidean (Bjorklund) distribuye pulsos uniformemente. L-System aplica reglas de reescritura recursiva. CA (Cellular Automata) evoluciona el patrón mediante reglas de vecindad celular en cada ciclo.",
    lsSeed: "Cadena inicial del L-System antes de aplicar las reglas de reescritura. X = golpe, O = silencio. Semillas más complejas generan patrones más densos desde las primeras iteraciones. La semilla define el carácter fundamental del patrón generado.",
    lsRuleA: "Regla de reescritura del L-System. Define cómo cada símbolo se expande en la siguiente iteración. Fibonacci (X→XO, O→X) genera la proporción áurea rítmica. Double (X→XX) duplica la densidad. Sparse (X→XOO) rarefacta. Complex (X→XOOX) maximiza la irregularidad.",
    lsIterations: "Número de veces que se aplica la regla de reescritura sobre la semilla. Cada iteración aumenta la complejidad del patrón. Iteración 1 = patrón simple, cercano a la semilla. Iteración 6 = patrón de alta densidad fractal. La longitud resultante se trunca o cicla para adaptarse a los steps de la pista.",
    lsRotation: "Desplazamiento del punto de inicio del patrón L-System generado. Equivale funcionalmente al parámetro Offset del modo euclidiano: permite escuchar el mismo patrón desde distintos puntos de entrada sin regenerarlo. Fundamental para encontrar la posición más idiomática del patrón dentro del compás.",
    caRule: "Número de regla del autómata celular unidimensional (notación de Wolfram). Determina cómo cada célula calcula su estado siguiente en función de sus vecinas. Rule 30 = caótica, aperiódica. Rule 90 = fractal simétrico, triángulos de Sierpiński. Rule 110 = computacionalmente universal. Rule 184 = modela tráfico y flujos.",
    caSeed: "Estado inicial del autómata antes de la primera evolución. Centro = una sola célula activa en el centro del grid. Borde = célula activa en el extremo izquierdo. Dos puntos = dos células activas simétricas. Aleatorio = distribución inicial estocástica al 30% de densidad. Determina la trayectoria completa de la evolución posterior.",
    caDensity: "Umbral de vecindad que filtra qué células activas suenan realmente. Densidad alta = solo suenan células con muchas vecinas activas, resultado más denso. Densidad baja = solo suenan células aisladas, resultado más esparso. Permite navegar entre la textura llena y el punteado rítmico sin cambiar la regla evolutiva subyacente.",
    caSpeed: "Número de ciclos completos del patrón que deben completarse antes de que el autómata evolucione al siguiente estado. Cada ciclo = el CA muta en cada vuelta del patrón. Cada 2 = el patrón se repite dos veces antes de mutar. Cada 4 = mayor estabilidad, cambios más espaciados. Controla la velocidad percibida de transformación.",
    noteMode: "Selector del algoritmo de elección de nota para la pista Tone. Euclidean = nota determinista por posición del step (comportamiento original). Markov = nota elegida por probabilidades de transición desde la nota anterior, usando las notas disponibles en noteIndices[].",
    markovStyle: "Define el carácter de la matriz de transición entre notas. Escala = alta probabilidad de movimiento por grados adyacentes, melodía conjunta. Saltos = preferencia por intervalos de cuarta/quinta, melodía disjunta. Flamenco = gravedad hacia la tónica y el semitono inferior, idiomático del modo frigio. IDM = distribución casi uniforme, máxima variabilidad. Cromático = preferencia por semitonos, máxima tensión.",
    markovTemperature: "Controla el grado de aleatoriedad en la elección de nota. Temperatura 0 = la nota de mayor probabilidad según la matriz se elige siempre (determinista). Temperatura 100 = todas las notas tienen probabilidad igual, la matriz se ignora. Valores intermedios mezclan el carácter del estilo con variabilidad estocástica. Análogo al parámetro temperature de los modelos de lenguaje.",
    markovAnchor: "Fuerza un retorno a la nota tónica (la más grave de las disponibles en noteIndices[]) cada N notas producidas por la cadena de Markov. OFF = la melodía puede alejarse indefinidamente de la tónica. Cada 4/8/16 = introduce periodicidad tonal que da sensación de frase musical. Esencial para mantener coherencia tonal en sesiones largas con temperatura alta.",
    markovShowMatrix: "Muestra la tabla de probabilidades de transición entre notas en tiempo real. Cada celda (i,j) representa la probabilidad de pasar de la nota i a la nota j. Los valores se expresan en porcentaje (0-100). La intensidad del color naranja es proporcional a la probabilidad. Permite visualizar exactamente qué define el carácter del estilo seleccionado.",
    // Phase 7 — Pan, Frequency Shifter, Spectral Delay, 3D Binaural, Envelope Crossfeed
    pan: "Posición de la pista en el campo estéreo. -1 = canal izquierdo exclusivo. 0 = centro (igual en ambos canales). +1 = canal derecho exclusivo. Implementado con Tone.Panner que usa un StereoPannerNode de Web Audio. El paneo afecta tanto al motor de síntesis como al sampler cargado.",
    freqShiftEnabled: "Activa el desplazamiento de frecuencias (Bode Frequency Shifter). A diferencia del pitch shift, que desplaza frecuencias proporcionalmente (multiplicación), el frequency shifter desplaza todas las frecuencias por una cantidad fija (suma). Esto rompe las relaciones armónicas y produce timbres inarmónicos. Implementado con bypass dual-gain para cero coloración cuando está desactivado.",
    freqShift: "Cantidad de desplazamiento en Hz. +100Hz suma 100Hz a cada frecuencia: un Do (262Hz) se convierte en 362Hz, un La (440Hz) en 540Hz. Los armónicos, antes en relación 1:2:3:4, pasan a relación no entera. El timbre pierde su carácter armónico y adquiere textura metálica e inarmónica. Rango -500 a +500Hz. 0Hz = bypass completo.",
    spectralDelayEnabled: "Bus de efectos global que aplica tiempos de delay diferentes por banda de frecuencia. La señal se divide en tres bandas (graves, medios, agudos) mediante filtros LPF/BPF/HPF, cada banda recibe su propio delay, y las tres se recombinan. El resultado es que los componentes espectrales de la señal llegan al oído en momentos distintos — el espectro se despliega en el tiempo.",
    spectralDelayWet: "Nivel de mezcla de la señal procesada por el Spectral Delay. 0 = solo señal seca, sin efecto. 1 = señal procesada al máximo. Valores intermedios mezclan ambas. El wet se aplica como ganancia en el nodo de salida del bus espectral antes de llegar al compresor master.",
    spectralDelayLowTime: "Tiempo de delay aplicado a las frecuencias graves (por debajo del crossover bajo, típicamente 200Hz). En el efecto \"waterfall\" clásico este valor es 0ms — los graves suenan de inmediato y actúan como ancla temporal del ritmo mientras los medios y agudos llegan después.",
    spectralDelayMidTime: "Tiempo de delay aplicado a las frecuencias medias (banda central entre los dos crossovers). El filtro BPF usa Q=0.5 para cobertura amplia y su frecuencia central se calcula automáticamente como media geométrica de las frecuencias de crossover bajo y alto. Rango 0-500ms.",
    spectralDelayHighTime: "Tiempo de delay aplicado a las frecuencias agudas (por encima del crossover alto, típicamente 4kHz). Los valores más altos (100-500ms) crean el efecto \"waterfall\" más pronunciado — los agudos llegan notablemente después que el cuerpo principal del sonido, como la reverberación natural de una sala grande donde los agudos se dispersan más lentamente.",
    binauralEnabled: "Activa el posicionamiento tridimensional usando HRTF (Head-Related Transfer Function). Reemplaza el Panner estéreo simple por Tone.Panner3D que usa el PannerNode de Web Audio con modelo HRTF. Las HRTFs simulan cómo el oído humano percibe la dirección del sonido según las reflexiones del pabellón auricular. Requiere auriculares para el efecto completo. Safari tiene implementación HRTF inconsistente.",
    binauralAzimuth: "Ángulo horizontal de la fuente sonora en grados. 0° = frente al oyente. 90° = derecha. 180° = detrás. 270° = izquierda. Se convierte internamente a coordenadas cartesianas X/Z: x = sin(azimuth) × distance, z = -cos(azimuth) × distance. La posición Y se mantiene en 0 (mismo plano horizontal que el oyente).",
    binauralDistance: "Distancia percibida de la fuente sonora al oyente en unidades abstractas (1-10). Controla el radio del posicionamiento cartesiano — a mayor distancia, mayor separación entre canales y mayor atenuación por el modelo de distancia inversa del PannerNode. Distancia 1 = muy cercano. Distancia 10 = lejano y pequeño.",
    crossfeedEnabled: "Modulación de la envolvente de amplitud de Cloud sobre el filtro de Tone. La energía RMS de la señal de Cloud se mide continuamente y se usa para controlar la frecuencia de corte del filtro de Tone. Cuando Cloud tiene grains activos con energía alta, el filtro de Tone se abre. Cuando Cloud calla, el filtro se cierra. El RMS se normaliza al rango 0-1 usando un factor de referencia de 0.3.",
    crossfeedBase: "Frecuencia de corte base del filtro de Tone cuando Cloud no tiene energía (RMS=0). Define el punto de partida de la modulación. Con Base baja (200-400Hz) el filtro empieza cerrado y Cloud lo abre hacia los agudos. Con Base alta (1500-2000Hz) el filtro ya está bastante abierto y Cloud modula en un rango más brillante.",
    crossfeedDepth: "Rango de modulación del filtro de Tone en Hz. Con RMS normalizado de Cloud = 1.0 (señal fuerte), el filtro sube hasta Base + Depth Hz. Con Depth=0 no hay modulación. Con Depth=8000Hz el filtro puede abrirse completamente cuando Cloud está activo. El valor final se clampea a 20000Hz para evitar aliasing.",
    // Phase 8 — Percussive Synthesis: Kick, Snare, Hat
    kickPitchDecay: "Velocidad con la que el pitch del MembraneSynth desciende desde su frecuencia inicial hasta la frecuencia base. Valores bajos (0.01-0.05) producen un kick electrónico seco — el barrido de pitch es casi imperceptible. Valores altos (0.2-0.5) producen el característico \"pum\" analógico donde el tono inicial es claramente audible antes de estabilizarse. Controla la naturaleza percusiva versus tonal del golpe.",
    kickOctaves: "Rango en octavas del barrido de pitch del MembraneSynth. Define cuánto desciende el pitch desde el inicio hasta la frecuencia base. Valores bajos (1-2) producen un kick plano con poco movimiento tonal — sonido más electrónico y estático. Valores altos (8-10) producen un barrido dramático de varias octavas — el kick \"cae\" desde una frecuencia alta hasta los graves con gran expresividad.",
    kickDecay: "Duración del cuerpo principal del kick en segundos. Controla cuánto tiempo persiste el sonido de la membrana después del ataque. Decay corto (0.1-0.2) = kick seco y percusivo, ideal para ritmos rápidos. Decay largo (0.6-1.0) = kick con sustain, más musical y menos percusivo, característico de géneros como dub o ambient.",
    kickClickType: "Tipo de ruido usado en la capa de click/transiente del kick. White noise = ataque brillante con máximo contenido en altas frecuencias, definición clara. Pink noise = ataque más cálido, energía distribuida perceptualmente de forma más uniforme, característico de kicks analógicos vintage. Brown noise = ataque oscuro y suave, graves predominantes, menos definición en el ataque pero más peso sub.",
    snareDecay: "Duración del envelope de la capa de ruido del snare en segundos. Decay muy corto (0.05-0.08) = snare seco y preciso, ideal para ritmos rápidos y estilos electrónicos. Decay medio (0.15-0.25) = snare natural con algo de cola. Decay largo (0.3-0.5) = snare con mucha resonancia, casi un rimshot o un snare de sala grande. Afecta directamente a cuánto \"espacio\" ocupa el snare en la mezcla.",
    snareNoiseType: "Espectro de ruido del snare. White noise = máxima brillantez, toda la energía distribuida por igual en todas las frecuencias — snare electrónico clásico (TR-909, LinnDrum). Pink noise = tonalmente más cálido, energía que decrece con la frecuencia, más cercano a snares acústicos reales. Brown noise = oscuro y con graves predominantes, completamente diferente a un snare convencional — más cercano a un tom o un hit percusivo grave.",
    snareBodyEnabled: "Activa una segunda capa de síntesis bajo el snare: un MembraneSynth que añade componente tonal al ruido. El snare real acústico funciona exactamente así — una membrana tensada (componente tonal) más los bordones metálicos (componente de ruido). Con Body activo, el snare deja de ser solo ruido y adquiere altura y cuerpo. El MembraneSynth se conecta al mismo filtro que el NoiseSynth.",
    snareBodyPitch: "Frecuencia base de la capa de MembraneSynth del snare en Hz. Frecuencias bajas (100-150Hz) añaden un cuerpo oscuro y con mucho peso, casi un tom. Frecuencias medias (150-250Hz) son el rango típico de un snare acústico real. Frecuencias altas (300-400Hz) añaden un cuerpo más nasal y brillante. La interacción entre esta frecuencia y el tipo de ruido define el carácter fundamental del snare.",
    snareBodyDecay: "Duración del envelope del MembraneSynth en la capa de cuerpo del snare. Si es menor que el decay del ruido, el cuerpo tonal aparece y desaparece rápidamente dejando que el ruido tenga la última palabra. Si es igual o mayor, el cuerpo tonal y el ruido se desvanecen juntos manteniendo la cohesión entre las dos capas. Permite separar la \"pegada\" inicial del cuerpo de la \"cola\" del ruido.",
    hatMode: "Selector del motor de síntesis del hi-hat. Noise = NoiseSynth (ruido blanco/rosa/marrón con envelope), mismo motor que el snare pero con decay más corto y filtro highpass. Metal = MetalSynth, síntesis FM de seis osciladores diseñada para simular superficies metálicas vibrantes. MetalSynth produce el espectro inarmónico característico de los platos y hats metálicos reales, con resonancias afinables.",
    hatHarmonicity: "Ratio entre las frecuencias del oscilador portador y el modulador en el MetalSynth. Valores bajos (0.1-1.0) producen relaciones inarmónicas extremas — el hat suena ruidoso y sin carácter tonal definido. Valores medios (2-5) producen el espectro metálico característico. Valores altos (7-10) aproximan relaciones más armónicas, el hat gana más tono y menos ruido. Análogo al harmonicity en FM synthesis.",
    hatModIndex: "Índice de modulación del MetalSynth. Controla la amplitud de la modulación FM, lo que determina la riqueza espectral del hat. Valores bajos (1-10) = espectro simple, hat más suave y menos agresivo. Valores altos (50-100) = espectro muy denso con muchos parciales, hat brillante, complejo y agresivo. En síntesis FM, el índice de modulación es el parámetro que más afecta al timbre.",
    hatResonance: "Frecuencia de resonancia del MetalSynth en Hz. Define dónde concentra su energía el plato simulado. Frecuencias bajas (100-500Hz) = hat oscuro y grave, más cercano a un platillo crash o ride. Frecuencias medias (1000-3000Hz) = hat equilibrado, rango típico de hi-hats acústicos. Frecuencias altas (4000-8000Hz) = hat muy brillante y aéreo. Interactúa con harmonicity y modIndex para definir el carácter espectral completo.",
    hatNoiseType: "Espectro de ruido del hi-hat en modo Noise. White noise = energía igual en todas las frecuencias, hat brillante y abierto tipo TR-909. Pink noise = energía que decrece 3dB/octava, hat más cálido y natural. Brown noise = energía concentrada en graves, hat oscuro y poco convencional. Cada tipo cambia drásticamente el carácter del hat sin alterar el envelope ni el filtro.",
    // Phase 9 — Freeze & Gated Reverb
    freezeEnabled: "Bus de efectos que acumula señal en un loop de feedback sin que decaiga. Implementado con Tone.Delay(80ms) + Tone.Filter(LP) + Tone.Gain(feedback) en loop manual. El filtro LP está dentro del loop de feedback — cada recirculación pierde agudos, oscureciendo la cola progresivamente. Cada nuevo golpe que llega al bus FRZ se suma al campo resonante existente sin borrar lo acumulado.",
    freezeFeedback: "Ganancia del loop de feedback del Freeze Bus (0.5-0.99). Controla cuánta señal recircula en cada iteración del loop. FB=0.95 significa que cada recirculación conserva el 95% de la energía — la cola decae muy lentamente. FB=0.99 es casi infinito — la señal acumulada persiste prácticamente sin decaer. FB=0.5 produce una cola que decae en pocas repeticiones.",
    freezeFilterFreq: "Frecuencia de corte del filtro paso-bajo dentro del loop de feedback del Freeze. Como el filtro está dentro del loop, cada recirculación atenúa las frecuencias por encima del corte. Con el tiempo, el campo congelado se vuelve progresivamente más oscuro y cálido — los agudos desaparecen primero, los medios después, quedando solo los graves en cola infinita. LP alto (10kHz+) = cola brillante. LP bajo (500Hz) = cola oscura y densa.",
    gatedEnabled: "Inserta un Tone.Gate después del reverb existente. El gate corta la señal de reverb abruptamente cuando cae por debajo del threshold — en lugar del decaimiento natural suave, el reverb termina de golpe. Usa crossfade con reverbNormalOut: cuando GRV activo, el path normal de reverb (decaimiento suave) se silencia y solo pasa la señal gateada.",
    gatedThreshold: "Nivel en dB por debajo del cual el gate corta la señal de reverb. Threshold alto (-10dB) = el gate se cierra rápidamente, casi al inicio del decaimiento — reverb muy corto y percusivo. Threshold bajo (-60dB) = el gate permite que el reverb decaiga casi completamente antes de cortar — efecto sutil. El valor óptimo para el efecto \"BOOM\" clásico es entre -30 y -40dB.",
    // Phase 10 — Extreme Looping
    extremeLoopEnabled: "Activa un micro-loop continuo en el GrainPlayer. Cuando está activo, el sampler entra en loop con loopStart, loopEnd y grainSize configurados por Size y Point. El step sequencer deja de disparar el sampler — el loop corre de forma autónoma mientras el transporte está activo. Un loop de N ms produce un tono aproximado de 1/N Hz: loop de 5ms ≈ 200Hz, loop de 10ms ≈ 100Hz.",
    extremeLoopSize: "Duración del micro-loop en milisegundos (1-50ms). Determina el pitch aproximado del tono resultante: pitch ≈ 1000/size Hz. Size=5ms ≈ 200Hz (Sol3). Size=10ms ≈ 100Hz (Sol2). Size=20ms ≈ 50Hz (Re1, sub-grave). Size=50ms produce un tono muy grave o una textura granular si el loop contiene variación interna. Valores muy pequeños (1-3ms) pueden producir artefactos de aliasing dependiendo del contenido del sample.",
    extremeLoopPoint: "Posición dentro del buffer donde empieza el micro-loop (0-1, normalizado a la duración total del sample). 0 = inicio del sample. 0.5 = mitad. 1 = final. El loopEnd se calcula automáticamente como Point + (Size/bufferDuration). Desplazar Point mientras el loop suena cambia el tono resultante porque el contenido espectral del sample varía en cada posición.",
    // Sampler mode
    oneShotMode: "Modo de playback del sampler donde la duración del trigger es la longitud completa del ROI (región de interés definida por sampleStart y sampleEnd), ignorando el tempo. En TRIGGER, el sample se corta cuando llega el siguiente step. En GATE, dura un sixteenth note. En ONE-SHOT, dura exactamente (sampleEnd - sampleStart) × bufferDuration — el sample suena completo sin importar el BPM o la densidad del patrón.",
    // Per-track EQ
    eqEnabled: "Activa un ecualizador de dos bandas (HPF + LPF) por pista. Implementado con Tone.Filter HPF y LPF en serie. Permite esculpir el rango frecuencial de cada elemento rítmico de forma independiente antes de los buses de efectos.",
    eqHpfFreq: "Frecuencia de corte del filtro paso-alto (High-Pass Filter) en Hz. Elimina frecuencias por debajo del corte. Rango: 20-2000Hz. Útil para limpiar graves no deseados en hats o snares, o para crear efectos de filtro progresivo en tiempo real.",
    eqLpfFreq: "Frecuencia de corte del filtro paso-bajo (Low-Pass Filter) en Hz. Elimina frecuencias por encima del corte. Rango: 1000-20000Hz. Útil para oscurecer sonidos, simular distancia acústica o crear barridos de filtro.",
    // Time Stretch
    stretchEnabled: "Activa el time-stretching granular en el sampler. Permite cambiar la velocidad de reproducción sin alterar el pitch. Implementado modificando el playbackRate del GrainPlayer mientras se compensa con detune.",
    stretchRate: "Factor de velocidad del time-stretch. 1.0 = velocidad original. 0.5 = mitad de velocidad (sample dura el doble). 2.0 = doble velocidad (sample dura la mitad). El pitch se mantiene constante mediante compensación granular.",
    // Normalize
    normalize: "Normaliza la amplitud del sample cargado a 0dBFS. Útil cuando los samples tienen niveles de grabación muy dispares. La normalización es perceptual — no altera el archivo original, solo la ganancia de reproducción.",
    // Sampler envelope
    samplerAttack: "Tiempo de ataque de la envolvente del sampler en milisegundos. Controla cuánto tarda el sample en alcanzar su volumen máximo desde el onset. 0ms = ataque inmediato, percusivo. 500ms = fade-in suave, más ambiental.",
    samplerDecay: "Tiempo de decaimiento de la envolvente del sampler en milisegundos. Controla cuánto tarda el sample en apagarse después del ataque. Valores bajos = cortes secos. Valores altos = colas largas y naturales.",
    // DJ Nudge
    nudge: "Control de offset en tiempo real para DJ performance. Permite desplazar el punto de inicio del patrón step a step, preparando un \"drop\" que se activa manualmente. Emula el nudge de los CDJ Pioneer.",
    // Percussive presets
    kickPreset: "Banco de presets de síntesis de kick. Cada preset configura simultáneamente pitchDecay, octaves, decay y clickType del MembraneSynth. Incluye presets de IDM, flamenco, industrial, house, jungle y más.",
    snarePreset: "Banco de presets de síntesis de snare. Cada preset configura decay, noiseType, bodyEnabled y parámetros de body. Incluye presets de IDM, flamenco, rimshot, brush, clap y variantes de densidad.",
    hatPreset: "Banco de presets de síntesis de hi-hat. Cada preset configura mode (noise/metal), decay, noiseType y parámetros FM del MetalSynth. Incluye presets de IDM, palmas flamencas, cymbal, tambourine y shaker.",
    // Hat decay
    hatDecay: "Duración del envelope del hi-hat en segundos. Controla la longitud de la cola del hat. Decay muy corto (0.02-0.05) = closed hat percusivo. Decay medio (0.1-0.2) = hat abierto con presencia. Decay largo (0.3+) = cymbal o ride con sustain prolongado.",
  } as PedagogyMicro,

  microLiterary: {
    pulses: "Cuántos golpes reparte el algoritmo de Euclides en el ciclo. E(5,12) genera el patrón de la Soleá flamenca; E(5,11) es territorio Autechre. Un solo pulso de diferencia separa siglos de tradición de la vanguardia algorítmica.",
    steps: "La longitud total del ciclo rítmico o \"anillo\". Define el espacio temporal donde los pulsos buscarán su equilibrio máximo. En el flamenco, el 12 es la cifra sagrada; en el IDM, los números impares rompen la tiranía del compás de 4/4.",
    offset: "Rota el patrón respecto al primer tiempo del compás. Es el \"nudge\" que desplaza el acento, permitiendo que una estructura estable se convierta en un síncope agresivo. Cambiar el offset es como desplazar el \"uno\" en una jam de hip-hop experimental.",
    probability: "La probabilidad de que un pulso programado llegue a sonar. Introduce el concepto de \"silencio activo\": el patrón existe en potencia, pero solo se manifiesta parcialmente. Es la base de la secuenciación generativa que evita la fatiga auditiva.",
    chaos: "Multiplica la incertidumbre de las probabilidades individuales. A niveles bajos, introduce dudas sutiles; a niveles altos, desintegra el patrón en una nube estocástica. Es el control del \"error controlado\" característico del glitch-hop.",
    evolve: "Permite que el patrón aprenda y cambie con cada ciclo. La mutación constante asegura que el ritmo nunca sea una foto fija, sino un organismo vivo que evoluciona. Es la encarnación del \"eterno retorno\" donde nada se repite exactamente igual.",
    bpm: "La velocidad del pulso maestro. Define la densidad de eventos por segundo y altera nuestra percepción del jitter: a BPMs altos, el caos se percibe como textura; a BPMs bajos, como duda humana.",
    swing: "El retraso determinista de los tiempos débiles, herencia directa de las MPC de Roger Linn. Crea ese \"empuje\" característico del boom-bap clásico. Es una rejilla rígida pero desplazada que invita al movimiento.",
    dynamics: "Controla el rango de intensidad (velocity) de los golpes. Una dinámica alta permite que el algoritmo \"acentúe\" de forma natural, emulando la intención de un percusionista. En el flamenco, el acento es la brújula que define el palo.",
    jitter: "Micro-timing gaussiano que desplaza los golpes milisegundos antes o después de su tiempo teórico. Rompe la perfección robótica del ordenador para entrar en el \"duende\" del error humano. Es la diferencia entre un metrónomo y un corazón.",
    volume: "El peso específico de cada pista en el espacio sonoro. Más que un control de nivel, es una herramienta de jerarquía rítmica. Define qué elemento es el ancla y cuál es el adorno.",
    delaySend: "Envía el sonido a un bucle de repeticiones que genera polirritmias fantasmales. El delay transforma un pulso seco en una cascada de ecos que refuerzan la geometría del patrón original.",
    reverbSend: "Sitúa el ritmo en un espacio físico o imaginario. En el IDM, la reverb se usa a menudo para \"emborronar\" la precisión matemática, creando atmósferas donde el ritmo parece emerger de una niebla industrial.",
    sampleRoi: "Define la \"Región de Interés\" dentro del archivo de audio sagrado. Permite realizar una micro-cirugía sonora, extrayendo solo el ataque de un cante o la cola de un glitch. Es el bisturí digital en acción.",
    pitch: "Transpone la frecuencia del sample, alterando su timbre y duración. Un pitch bajo puede convertir un chasquido en un bombo profundo; un pitch alto transforma un quejío en un micro-glitch de alta frecuencia.",
    grainSize: "El tamaño de las partículas en la síntesis granular. Granos pequeños crean texturas metálicas y nubes de polvo sonoro; granos grandes permiten reconocer fragmentos del audio original. Es la atomización del tiempo.",
    overlap: "Cuántos granos se superponen entre sí. Define la densidad de la \"nube\" sonora. Un overlap alto crea texturas sedosas y continuas; un overlap bajo genera un tartamudeo rítmico (stutter) puramente IDM.",
    spray: "La dispersión aleatoria del punto de lectura de los granos. Introduce un caos espacial y temporal que desdibuja el origen del sonido. Es la técnica definitiva para convertir una voz flamenca en una atmósfera abstracta.",
    bitCrush: "Reduce la resolución digital del sonido, introduciendo ruido de cuantización y armónicos agresivos. Evoca la estética de los samplers de 8 bits y la degradación industrial del lo-fi experimental.",
    reverbMix: "El grado en que el ritmo habita un espacio imaginario. A cero, cada golpe es un hecho seco y presente; al máximo, el patrón se disuelve en su propia reverberación como un eco en una catedral abandonada. Es la distancia entre el oyente y el evento sonoro.",
    delayMix: "Cuánto protagonismo tienen los ecos respecto al golpe original. Un delay sutil es como una sombra que confirma la existencia del sonido; un delay dominante convierte cada onset en el inicio de una cadena infinita de fantasmas rítmicos.",
    delayFeedback: "La memoria del eco. Con feedback bajo, cada repetición es un recuerdo que se desvanece; con feedback alto, el eco se alimenta de sí mismo hasta generar una espiral sonora autorreferente. En el dub jamaicano, el feedback extremo era un acto de rebeldía contra la linealidad del tiempo.",
    fxHighPass: "Un filtro que elimina los graves de la cadena de efectos, como si la reverberación perdiera su peso gravitatorio. Sube el corte y los ecos se vuelven etéreos, espectrales, como escuchar el ritmo a través de una pared. Herramienta esencial del minimalismo electrónico.",
    fxLowPass: "Un filtro que recorta los agudos de los efectos, suavizando las aristas de cada eco y reverberación. Es la niebla que difumina los contornos del sonido. En el lo-fi, el paso-bajo es el equivalente sonoro de una fotografía desenfocada: sugiere más de lo que muestra.",
    monitorTemporal: "El electrocardiograma del ritmo. Cada punto es la desviación de un golpe respecto a su tiempo teórico. Una línea recta es un metrónomo; una línea errática es un corazón que late con emoción. Aquí se ve, literalmente, la diferencia entre programar y tocar.",
    monitorDistribution: "El mapa de calor de la energía rítmica. Revela dónde se concentran los golpes a lo largo del tiempo, dibujando los acentos que emergen del caos probabilístico. Es como ver la fotografía de larga exposición de un patrón que nunca se repite exactamente igual.",
    monitorRange: "El termómetro de la expresividad. Un rango dinámico estrecho es un robot; un rango amplio es un ser humano que acaricia y golpea el instrumento. Este monitor muestra si tu patrón tiene 'respiración' o si está atrapado en la monotonía de la intensidad plana.",
    monitorScatter: "La huella dactilar del groove. Cada punto representa un golpe en el espacio bidimensional del cuándo (timing) y el cuánto (intensidad). Los clusters revelan hábitos; la dispersión revela libertad. Un percusionista de flamenco y una caja de ritmos TR-808 dibujan constelaciones radicalmente distintas.",
    patternSync: "El reloj cósmico de los ritmos cruzados. Mide cuánto tarda el universo polirrítmico en volver a su estado inicial — como los planetas alineándose en una conjunción. Cuando el número es bajo, los patrones se abrazan con frecuencia; cuando es alto, estás componiendo una pieza que no se repite en la escala de la memoria humana.",
    rhythmicEntropy: "El termómetro de lo impredecible. Resume en un solo número cuánta 'vida' tiene el sistema: ¿es un metrónomo o un organismo? La entropía rítmica combina el caos, la mutación y el micro-timing en un índice que va desde la certeza absoluta hasta el borde del caos creativo.",
    mcmValue: "El número mágico: cuántos pasos deben pasar antes de que todos los patrones vuelvan a coincidir en el 'uno'. Con ciclos de 7, 11 y 13, el eclipse rítmico tarda 1001 pasos. Es la arquitectura invisible que define si tu poliritmia tiene memoria corta o se despliega como una galaxia espiral.",
    syncImpact: "La huella gravitatoria de cada pista en el sistema. Un impacto alto significa que esa pista es la responsable de la complejidad del ciclo global — es el número primo que impide la simplificación. Eliminarla sería como quitar la especia secreta de un plato: todo se vuelve predecible.",
    phaseRadar: "Un radar circular donde cada pista es un satélite en órbita. Los puntos giran a velocidades distintas según la longitud de su ciclo, y el momento en que todos se alinean es el 'eclipse' rítmico. Es la visualización más intuitiva de la poliritmia: ves literalmente cómo los tiempos se persiguen y se encuentran.",
    eclipseCountdown: "El reloj de arena del eclipse rítmico. Cuenta los segundos que faltan para que todos los satélites se alineen en el mismo meridiano — el momento donde la poliritmia colapsa brevemente en unísono antes de volver a divergir. En ciclos cortos es un metrónomo cósmico; en ciclos largos, es una promesa lejana que transforma la escucha en una espera contemplativa.",
    hitRate: "El pulso vital del patrón. Mide cuántos golpes programados realmente llegaron a sonar, revelando la tensión entre intención y azar. Al 100% el algoritmo manda; al 50% el silencio y el sonido negocian en igualdad de condiciones. Es el indicador más directo de cuánto 'aire' respira tu ritmo — cuánto espacio le has dado al fantasma del silencio para habitar entre los golpes.",
    fmRatio: "El ratio FM es la distancia entre dos voces que cantan juntas. Cuando es un número limpio, armonizan. Cuando es irracional, crean tensión — como dos relojes que nunca sincronizan del todo.",
    fmIndex: "El Index FM es cuánto tiembla la voz. A 0 es cristalina. A 50 es un grito.",
    wfAmount: "El fold es origami sónico. Doblar la onda una vez crea un pliegue. Doblarla ocho veces crea una textura que el oído no puede desenredar.",
    wfSymmetry: "La simetría del fold decide si la onda respira igual por los dos lados. Rota hacia un lado y el sonido pierde su equilibrio — como una silla con una pata más corta.",
    addPartials: "Los parciales son las voces del coro. Con 2 cantan al unísono y la octava. Con 8 cantan todas las voces de la serie armónica — la física del sonido hecha visible.",
    addBrightness: "El brillo es cuánto poder cedes a los armónicos agudos. A 0 el fundamental manda. A 1 es una democracia espectral — todos los armónicos votan igual.",
    arRate: "Cuando el modulador supera 20Hz deja de ser movimiento y se convierte en sonido. El LFO ya no balancea la nota — la infecta con nuevas frecuencias.",
    arDepth: "La profundidad AR decide qué tan lejos viaja la infección. A 0 no hay enfermedad. A 3000Hz el sonido ya no recuerda de dónde vino.",
    ratchet: "El redoble digital. Cada step puede contener un rápido aleteo de golpes que decaen como el rebote de una baqueta sobre el parche — o como los pies de un bailaor que no pueden quedarse quietos. Es la diferencia entre un golpe seco y una ráfaga. En el flamenco, el zapateado vive aquí.",
    metricModulation: "Cambiar de marcha sin soltar el acelerador. Una modulación métrica convierte lo que era subdivisión en beat principal — el tresillo se convierte en pulso, y lo que sonaba a 120 de repente late a 180. Stravinsky hacía esto con orquestas; Nancarrow, con pianolas. Tú, con un botón.",
    layer2Blend: "La mezcla entre dos mundos sonoros superpuestos. A un lado, el golpe que conoces; al otro, una capa nueva que lo enriquece o lo contradice. Girar este control es como añadir una segunda voz a un cante: puede armonizar o crear una tensión deliciosa.",
    layer2Pitch: "La afinación independiente de la segunda capa. Mientras Layer 1 mantiene su nota, Layer 2 puede subir una quinta, bajar una octava, o flotar en un intervalo disonante. Es como dos cuerdas de guitarra que suenan juntas pero viven en universos tonales distintos.",
    layer2Offset: "El desfase temporal entre las dos capas — el 'flam' digital. A cero golpean juntas; con unos milisegundos de separación, una llega antes que la otra como un eco adelantado. Es el micro-timing dentro del micro-timing: ritmo dentro de un solo golpe.",
    layer2Filter: "El velo que cubre la segunda capa. Baja el filtro y Layer 2 se convierte en un murmullo oscuro bajo la superficie del golpe principal — presente pero misterioso, como un bordón que se siente más de lo que se escucha.",
    padVoices: "Las voces del coro sintético. Tres voces son un trío íntimo; siete son un ensemble que llena el espacio con batimientos y microinterferencias. Cada voz es casi igual a las demás — pero ese 'casi' es todo. Como un coro que canta al unísono pero donde cada garganta tiene su propia imperfección.",
    padDetune: "Cuánto se desvían las voces entre sí. Sin detune, cantan en perfecto unísono — matemáticamente frío. Con detune, cada voz tira ligeramente hacia un lado, creando un coro cálido que late y respira. Es la diferencia entre un sintetizador y un Juno-60.",
    padAttack: "La velocidad con la que el acorde emerge del silencio. Un ataque rápido marca el ritmo con claridad; un ataque lento hace que el pad suba como una marea — ya está ahí antes de que te des cuenta. Define si el sonido es percusión disfrazada o atmósfera pura.",
    droneFeedback: "Cuánto tiempo vive el bordón antes de desvanecerse. Con feedback bajo, es un destello que se apaga. Con feedback alto, es una cuerda que vibra indefinidamente, sostenida por su propia resonancia — como la cuerda del bordón de una zanfona que nunca para de girar.",
    droneFilterFreq: "El color del bordón eterno. Oscuro es como una nota de contrabajo en una cueva; brillante es como un armónico de sitar que corta el aire. Este filtro decide si tu drone es tierra o cielo.",
    ksDecay: "Cuánto vibra la cuerda virtual después de ser pulsada. Corto y seco como un pizzicato de contrabajo. Largo y sostenido como un sitar que parece no acabar nunca. La física de la cuerda, simulada con un delay y un filtro — elegancia algorítmica de 1983.",
    ksBrightness: "El material de la cuerda imaginaria. Oscuro es tripa de oveja en una vihuela del siglo XVI. Brillante es acero en una guitarra eléctrica. Cada pasada por el loop pierde un poco de brillo — exactamente como una cuerda real que se apaga desde los agudos.",
    modalBody: "El cuerpo que vibra cuando lo golpeas. Una campana tiene frecuencias que no se llevan bien entre sí (inarmónicas). Una cuerda las tiene en perfecta proporción (armónicas). Una placa está entre ambos mundos. Cada uno tiene su propia firma sonora — su ADN vibratorio.",
    modalDecay: "Cuánto tiempo resuenan los modos después del golpe. Corto es un golpe de madera — toc. Largo es un gong tibetano que canta durante minutos. Los modos agudos siempre mueren antes que los graves — la naturaleza no permite otra cosa.",
    ambientVolume: "El nivel de la niebla sonora que envuelve el ritmo. Sutil y es un aroma que apenas percibes. Dominante y el ritmo emerge desde la textura como una forma que se dibuja en la niebla. Es la distancia entre primer plano y paisaje.",
    ambientSpeed: "La velocidad a la que respira la textura ambiente. Lenta y el tiempo se dilata — cada grano de sonido se estira como un amanecer. Rápida y la textura se acelera, se granula, se convierte en lluvia. El ritmo euclidiano sigue su camino; la textura vive en su propio tiempo.",
    roundRobin: "La imperfección que da vida. Cada golpe suena ligeramente distinto al anterior — como un percusionista que nunca golpea exactamente igual dos veces. En la pista tonal, las notas rotan como cuentas de un collar: el patrón rítmico es el hilo, las notas son las piedras que cambian de color con cada vuelta.",
    phaseDrift: "El experimento de Steve Reich hecho botón. Dos patrones idénticos que empiezan juntos y, golpe a golpe, se van separando — como dos relojes que caminan a velocidades casi iguales. Lo que empieza como unísono se convierte en canon, luego en caos armónico, y eventualmente vuelve a encontrarse. Es la paciencia convertida en composición.",
    cloudMode: "El alma de la pista Atmosphere. En modo Granular, el sample se fragmenta en partículas que flotan como polvo en un haz de luz. En modo Eno, el sample se multiplica en cuatro ecos fantasma que viven y mueren a ritmos distintos — como cuatro velas encendidas a la vez, cada una con su propia mecha. Brian Eno soñó con música que se genera sola; aquí, el sample es la semilla.",
    enoSpeed: "La respiración del modo Eno. Lenta y las cuatro capas se estiran como nubes en un cielo de verano, cambiando tan despacio que apenas notas la transformación. Rápida y el sample se fragmenta en un caleidoscopio de ciclos cortos que se atropellan entre sí. El secreto está en las duraciones irracionales: nunca se alinean del todo, y en esa imperfección vive la música.",
    // Phase 4 — L-System, Cellular Automata, Markov
    patternMode: "Tres filosofías del tiempo: la justicia matemática de Euclides, la gramática que se devora a sí misma del L-System, y el autómata que decide su propio destino célula a célula.",
    lsSeed: "El primer fonema antes de que el lenguaje se desplegara. Todo el árbol filogenético del ritmo contenido en una sola sílaba.",
    lsRuleA: "La ley que transforma. Como el ADN que contiene no un cuerpo sino las instrucciones para construir un cuerpo, esta regla no es el ritmo sino el proceso que lo engendra.",
    lsIterations: "El tiempo dentro del tiempo. Cuántas veces la regla se aplica a sí misma antes de que el patrón cristalice en el golpe que escuchas.",
    lsRotation: "El mismo collar de cuentas, otra cuenta de inicio. El patrón no cambia — cambia dónde decides que empiece el mundo.",
    caRule: "El nombre de una ley del universo. Wolfram numeró 256 posibles cosmos; estos cuatro contienen música.",
    caSeed: "El Big Bang del patrón. De dónde surge la primera perturbación que, propagándose según la ley, construirá todo lo que vendrá.",
    caDensity: "El volumen del silencio. La regla genera todo; la densidad decide qué parte de ese todo alcanza el oído.",
    caSpeed: "El metabolismo del patrón. Con qué frecuencia el autómata decide que ha vivido suficiente en su estado actual y se transforma en otro.",
    noteMode: "Dos formas de habitar una escala: la mappa mundi que asigna cada territorio a cada paso, o el caminante que decide adónde ir según dónde está.",
    markovStyle: "El temperamento del músico imaginario que vive en la cadena de Markov. Su forma de moverse por el espacio tonal: con pasos prudentes, con saltos atrevidos, con el instinto flamenco de volver siempre a casa.",
    markovTemperature: "El calor que desordena los cristales. A temperatura cero, el sistema encuentra su estado de mínima energía y se queda quieto. A temperatura máxima, todo es igualmente posible y nada es probable.",
    markovAnchor: "La cuerda que ata al explorador a la entrada de la cueva. Sin ella, la melodía puede adentrarse tanto en el laberinto que olvida cómo salir. Con ella, cada cierto tiempo, vuelve a la luz.",
    markovShowMatrix: "El mapa del pensamiento del algoritmo. Ver la matriz es ver cómo decide, antes de que decida. La diferencia entre escuchar música y entender por qué suena así.",
    // Phase 7 — Pan, Frequency Shifter, Spectral Delay, 3D Binaural, Envelope Crossfeed
    pan: "El espacio horizontal del sonido. En el silencio entre los auriculares, el ritmo puede venir de cualquier punto del horizonte — izquierda, derecha, o desde el centro exacto donde convergen todos los pulsos.",
    freqShiftEnabled: "La diferencia entre transponer y desplazar: transponer sube todos los pisos del edificio proporcionalmente, desplazar mueve el edificio entero al número de la calle siguiente. El resultado ya no es música en ningún sentido occidental del término — y eso es exactamente lo que lo hace interesante.",
    freqShift: "Pequeños desplazamientos, grandes consecuencias. +50Hz convierte una cuerda de guitarra en metal oxidado. +200Hz convierte una voz en maquinaria. El umbral entre lo musical y lo industrial es más fino de lo que parece.",
    spectralDelayEnabled: "La lluvia cae toda a la vez pero la escuchas en capas: el trueno llega después del rayo, los agudos de la tormenta después de los graves. El Spectral Delay hace lo mismo con cualquier sonido: lo convierte en una narración temporal de su propio contenido espectral.",
    spectralDelayWet: "Cuánto del tiempo se filtra hacia el sonido. Con wet bajo, el efecto es un fantasma detrás de la señal original. Con wet alto, el original desaparece y solo quedan sus ecos espectrales escalonados.",
    spectralDelayLowTime: "El cimiento que no espera. Los graves son la gravedad del sonido — llegan primero porque son lo más pesado, lo más terrenal, lo más cercano al golpe físico en el suelo.",
    spectralDelayMidTime: "La voz del sonido, que llega cuando los graves ya han asentado la base. El medio es donde la mayoría de los instrumentos viven — escucharlo llegar 80ms después del golpe inicial es escuchar el sonido desplegarse como un abanico.",
    spectralDelayHighTime: "El brillo que llega tarde, como la luz que se demora en rebotar por las esquinas de la habitación. Los agudos son los más viajeros del espectro — dejarlos llegar en su propio tiempo es dejar que el sonido cuente su historia completa.",
    binauralEnabled: "El sonido que existe en el espacio, no en el disco. Con auriculares, el 3D Binaural rompe la ilusión de que la música vive \"entre los oídos\" y la proyecta al mundo exterior — delante, detrás, arriba. El ritmo puede girar alrededor de tu cabeza como un planeta.",
    binauralAzimuth: "El ángulo de llegada del sonido. 0° es la máscara directa, el frente donde los ojos miran. 90° es el costado del pensamiento. 180° es lo que viene de donde no se mira. Girar el azimuth lentamente es hacer que el ritmo te circunde.",
    binauralDistance: "Qué tan lejos vive el sonido de ti. Distancia 1 es el ritmo que te respira en el oído. Distancia 10 es el ritmo que escuchas desde el otro lado de una plaza desierta a las 3 de la mañana.",
    crossfeedEnabled: "La conversación entre los dos mundos sonoros de la app: el ritmo granular de Cloud dicta la apertura tonal de Tone. Es el principio del vocoder sin su complejidad técnica — el espacio sonoro controlando la melodía, la textura gobernando el timbre.",
    crossfeedBase: "El silencio tonal. La frecuencia donde Tone descansa cuando Cloud no habla — el punto de partida del diálogo entre los dos motores. Aquí vive Tone antes de que Cloud lo despierte.",
    crossfeedDepth: "Cuánto puede hablar Cloud a través de Tone. Depth pequeño es un susurro — apenas perceptible, sutil. Depth grande es una orden: cuando Cloud explota en grains, Tone abre su boca espectral y canta todo lo que puede.",
    // Phase 8 — Percussive Synthesis: Kick, Snare, Hat
    kickPitchDecay: "La caída del pitch es la firma del kick. En 0.01 es un golpe sin memoria, presente y ya ido. En 0.5 es una afirmación — el sonido recuerda de dónde vino antes de instalarse en su frecuencia final. La diferencia entre un kick de Roland TR-808 y un bombo de orquesta sinfónica es, en parte, este número.",
    kickOctaves: "El tamaño del viaje tonal del kick. Octaves=1 es un paso. Octaves=10 es un salto desde el tejado hasta el sótano. La gravedad del golpe se mide en cuánto cae antes de llegar al suelo.",
    kickDecay: "El tiempo que el kick decide quedarse. Corto es un visitante puntual — llega, golpea, se va. Largo es un invitado que se queda resonando mientras la siguiente nota ya ha llegado. En el dub, el kick nunca termina de irse.",
    kickClickType: "El carácter del primer milisegundo. White es el chasquido de un látigo. Pink es la bofetada de una mano abierta. Brown es el golpe sordo de un puño contra una mesa de madera. El mismo kick, tres personalidades del ataque.",
    snareDecay: "Cuánto tiempo el snare habita el silencio después del golpe. Un snare seco es una coma. Un snare largo es un punto y aparte que obliga a la siguiente nota a esperar.",
    snareNoiseType: "El color del snare. White es fluorescente, todo brillo y aristas. Pink es la luz de una tarde nublada — completo pero sin agresividad. Brown es la oscuridad antes de que tus ojos se acostumbren.",
    snareBodyEnabled: "El snare sin cuerpo es una queja. Con cuerpo es una afirmación. La membrana que vibra detrás del ruido es lo que convierte el crack en un sonido que reconoces como \"snare\" aunque no hayas oído ninguno igual antes.",
    snareBodyPitch: "La nota que nadie está escuchando conscientemente pero que define el carácter del snare. Baja, el snare es gordo y oscuro. Alta, el snare es tenso y urgente. El cerebro procesa ambas capas a la vez y las combina en una sola identidad sonora.",
    snareBodyDecay: "El tempo del cuerpo, independiente del tempo del ruido. Cuando los dos terminan juntos el snare es uno. Cuando terminan en tiempos distintos el snare es dos cosas que se despiden por separado.",
    hatMode: "La diferencia entre el hat como ruido y el hat como instrumento. En modo Noise es abstracto — una cortina de frecuencias. En modo Metal es concreto — metal vibrando, con su propia voz y sus propios armónicos imposibles de nombrar.",
    hatHarmonicity: "El grado de afinación del metal. Bajo, el hat no tiene opinión sobre las notas — es ruido con textura. Alto, empieza a tener preferencias tonales, a querer estar en clave. El metal real está en algún punto intermedio, y ese punto intermedio es exactamente donde vive la magia.",
    hatModIndex: "La agresividad del metal. Bajo es el hat que pide permiso antes de sonar. Alto es el hat que irrumpe en la mezcla sin anunciarse, llenando el espectro de presencia. Entre los dos extremos están todos los hats que alguna vez has escuchado en IDM.",
    hatResonance: "La frecuencia donde el metal quiere cantar. Cada plato real tiene una resonancia fundamental — el punto donde vibra con más energía cuando lo golpeas. Aquí defines ese punto para el hat virtual. Es como elegir de qué metal está hecho.",
    hatNoiseType: "El color de la cortina de ruido. White es la estática de un televisor sin señal a las 3AM. Pink es la lluvia cayendo sobre un tejado de zinc. Brown es el rumor sordo del viento dentro de una cueva. El mismo hat, tres climas sonoros.",
    // Phase 9 — Freeze & Gated Reverb
    freezeEnabled: "El reverb que no olvida. Mientras el reverb convencional decae, el Freeze acumula — cada golpe añade una capa al campo sonoro que ya estaba ahí. Con el tiempo, la pista percusiva desaparece dentro de su propio eco, que sigue creciendo sin límite hasta que bajas el feedback o apagas el send.",
    freezeFeedback: "El grado de inmortalidad del sonido. En 0.99 nada muere — cada golpe se suma a todos los anteriores y el campo crece sin fin. En 0.5 el pasado se desvanece rápido, solo persiste lo más reciente. El punto entre los dos es donde el campo sonoro respira — crece y mengua en equilibrio.",
    freezeFilterFreq: "La temperatura de la memoria. Con LP alto el campo congelado recuerda cada detalle — brillante, frío, metálico. Con LP bajo, el tiempo devora los agudos y solo quedan los graves — cálido, oscuro, amnésico. El filtro es el tiempo que pasa dentro del loop.",
    gatedEnabled: "El reverb que no termina — termina. La diferencia entre \"boooooom\" y \"BOOM\". Phil Collins lo popularizó en los 80, IDM lo usa de forma irónica: tomar la herramienta más kitsch de la producción comercial y ponerla al servicio de la complejidad rítmica. El corte abrupto crea un espacio negativo — el silencio después del gate es tan musical como el reverb antes de él.",
    gatedThreshold: "El punto de silencio. Dónde decide el gate que el reverb ya ha dicho suficiente. Alto es implacable — apenas empieza, ya terminó. Bajo es permisivo — deja hablar al reverb hasta que casi no queda nada, y entonces lo silencia. El drama del gated reverb vive en ese corte: el momento exacto donde el espacio desaparece.",
    // Phase 10 — Extreme Looping
    extremeLoopEnabled: "El sampler que se devora a sí mismo. Un fragmento microscópico del audio original — tan pequeño que deja de ser un sonido y se convierte en un tono — en loop infinito. La muestra de batería se convierte en un dron. El habla se convierte en nota. Es síntesis por accidente: extraer frecuencia de lo que solo era timbre.",
    extremeLoopSize: "El tamaño del instante que se repite. Pequeño, el loop es una nota definida — el sampler habla con voz propia. Grande, el loop es una textura — un fragmento con vida interior que late a su propio ritmo. El slider de Size es la frontera entre síntesis y granular.",
    extremeLoopPoint: "Dónde dentro del sonido vivir para siempre. Cada punto del sample tiene su propio carácter espectral — aquí la voz es nasal, aquí es oscura, aquí hay un chasquido. Mover el Point mientras suena es explorar la geografía interna del audio, habitando un instante diferente cada vez.",
    // Sampler mode
    oneShotMode: "El sample que termina en su propio tiempo, no en el del reloj. En TRIGGER el tempo es tirano — corta todo lo que no cabe en el intervalo. En ONE-SHOT el sample es soberano — comienza cuando el patrón lo llama, pero termina cuando él decide. Útil para voces, frases melódicas, y cualquier cosa que tenga su propio arco interno.",
  } as PedagogyMicro,

  meso: {
    polyrhythm: {
      title: "Poliritmia Emergente",
      condition: "Steps de 2+ pistas son diferentes",
      template: "Estás operando en un ciclo de {p1}/{s1} contra {p2}/{s2}. Esta interferencia crea un patrón largo que tarda mucho en repetirse, una técnica clave en el IDM de finales de los 90 como el de *Autechre* en 'LP5'. La complejidad no nace del caos, sino del cruce de dos órdenes simples."
    },
    mcmEclipse: {
      title: "El Ciclo del Eclipse (MCM)",
      condition: "MCM (LCM) de los steps > 128",
      template: "El sistema actual tiene un Mínimo Común Múltiplo de {lcm} pasos. Esto significa que el \"eclipse\" rítmico (donde todos los tracks vuelven a coincidir en el uno) tarda {lcm} pulsos en ocurrir. Estás construyendo una arquitectura temporal que desafía la memoria a corto plazo del oyente."
    },
    primeAesthetics: {
      title: "La Estética del Primo",
      condition: "Algún valor de Steps es un número primo",
      template: "Al usar un ciclo de {p}/{s} pasos con base prima, estás rompiendo la simetría binaria de la música occidental. Los números primos son los ladrillos del IDM más cerebral, ya que obligan al cerebro a buscar un patrón que se desplaza constantemente respecto al pulso de 4/4."
    },
    entropy: {
      title: "Índice de Vida (Entropía)",
      condition: "Chaos + Evolve + Jitter > umbral alto",
      template: "Con una entropía combinada alta, el patrón ha dejado de ser una secuencia para convertirse en un organismo. La suma de mutación cíclica y jitter gaussiano emula la \"imperfección orgánica\" que el colectivo *Anticon* buscaba en sus producciones de hip-hop abstracto."
    },
    flamenco: {
      title: "Raíz Flamenca",
      condition: "Preset de palo flamenco cargado",
      template: "Este patrón E({p}, {s}) es la base rítmica de la tradición. Nota cómo los acentos definen la identidad del palo. Estás usando un algoritmo del siglo XXI para invocar una estructura emocional con siglos de historia."
    }
  } as Record<string, PedagogyMeso>,

  macro: {
    euclideanRhythm: {
      title: "¿Qué es un ritmo euclidiano?",
      content: "El algoritmo de Bjorklund, originalmente diseñado para aceleradores de partículas, distribuye un número de pulsos en un ciclo de la forma más uniforme posible. Esta \"distribución óptima\" no es solo una curiosidad matemática; es el código fuente de casi todos los ritmos tradicionales del mundo. Desde el Shiko africano hasta la rumba cubana, la humanidad ha buscado intuitivamente la geometría que Euclides describió hace milenios. En esta app, esa geometría es el lienzo sobre el que pintas con probabilidades y ruido."
    },
    soleaCenter: {
      title: "La Soleá como centro gravitatorio",
      content: "La Soleá, con su ciclo de 12 tiempos y su estructura de acentos desplazados, es el \"agujero negro\" rítmico del flamenco. Matemáticamente, es una de las estructuras más ricas que se pueden generar con permutaciones de grupos de 2 y 3. Su \"distancia de intercambio\" respecto a otros ritmos como la Bulería es mínima, lo que demuestra que el flamenco es un sistema dinámico de transformaciones topológicas. Al manipular los pulsos aquí, estás recorriendo el mismo mapa de tensiones que un palmero profesional."
    },
    complexityResistance: {
      title: "Complejidad como resistencia",
      content: "En un mundo dominado por el 4/4 de la música comercial, el uso de polirritmias y métricas impares es un acto de resistencia cultural. El IDM y el flamenco comparten esta naturaleza: ambos son lenguajes de minorías que exigen una escucha activa y un compromiso intelectual. La complejidad no busca confundir, sino crear un espacio donde la predicción fácil es imposible. Cuando configuras un patrón que tarda 500 pasos en repetirse, estás reclamando la soberanía sobre tu propio tiempo."
    },
    duendeGlitch: {
      title: "Duende y Glitch: El accidente feliz",
      content: "El \"duende\" flamenco es ese momento inefable donde el error y la pasión se encuentran; el \"glitch\" es su equivalente electrónico, donde el fallo de la máquina revela una belleza inesperada. Ambos conceptos celebran la pérdida de control. Una secuencia euclidiana perfecta es solo matemáticas; una secuencia euclidiana con jitter, caos y mutación es arte. Esta máquina está diseñada para que busques ese punto de ruptura donde la lógica se desmorona y aparece la emoción."
    },
    silenceInstrument: {
      title: "El silencio como instrumento",
      content: "En la música generativa, lo que no suena es tan importante como lo que suena. La rejilla de pasos es un mapa de posibilidades, y la probabilidad es el filtro que decide qué se manifiesta. El silencio entre los pulsos euclidianos crea el \"espacio negativo\" necesario para que el ritmo respire. Como en el cante jondo, los silencios (los \"respiros\") son los que dan peso a la nota siguiente. No estás programando sonidos, estás esculpiendo el silencio."
    },
    soleaAlgorithm: {
      title: "De la Soleá al algoritmo",
      content: "La convergencia entre la tradición oral del flamenco y los algoritmos de computación no es una coincidencia, sino una propiedad emergente de la física del ritmo. Ambos sistemas buscan resolver el mismo problema: cómo dividir el tiempo de forma que sea a la vez estable y sorprendente. La Euclidean IDM Machine demuestra que un productor de laptop en Bristol y un guitarrista en Jerez están, en esencia, ejecutando procesos mentales similares. El código es simplemente una nueva forma de escribir una partitura que ya estaba grabada en nuestros huesos."
    },
    granularCante: {
      title: "Síntesis granular y cante",
      content: "\"El cante flamenco es, en esencia, síntesis granular orgánica\". Esta frase de la tesis central del proyecto explica cómo los melismas y vibratos de un cantaor fragmentan la voz en micro-eventos tonales. Al usar el motor de nubes de esta app sobre muestras de voz, no estás destruyendo el cante, lo estás expandiendo. Estás permitiendo que un segundo de emoción se congele en una textura infinita, permitiendo un análisis forense de la pasión humana a través de la tecnología granular."
    },
    anticonRap: {
      title: "Anticon: El rap como IDM",
      content: "El colectivo Anticon (Doseone, Jel, Alias) revolucionó el hip-hop al tratar la MPC no como un metrónomo, sino como un instrumento de improvisación libre, a menudo ignorando la cuantización. Su estética de \"arritmia controlada\" es el puente perfecto entre el IDM y el hip-hop experimental. Esta app captura ese espíritu al permitir que el Jitter y el Chaos rompan la rejilla. Cuando el ritmo parece \"arrastrarse\" o \"tropezar\", estás invocando la libertad creativa de la escena indie-hop de Oakland de los años 2000."
    }
  } as Record<string, PedagogyMacro>
};

export function getMicroText(key: string, voice: PedagogyVoice): string {
  return voice === 'literary'
    ? (PEDAGOGY.microLiterary[key] ?? PEDAGOGY.micro[key] ?? '')
    : (PEDAGOGY.micro[key] ?? '');
}
